# frozen_string_literal: true
# https://github.com/huanzochen/ruby_playground

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'rubocop', '0.48.1', require: false

# gem "rails"
